name: Pull Request Jobs
on:
  merge_group:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  test:
    name: Test Pull Request
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup pnpm
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          cache: true
          require-lockfile: true
      - name: Build Package
        run: pnpm build
      - name: Check Formatting
        run: pnpm format:check
      - name: Lint Code
        run: pnpm lint:ci
